CitamChoir/Controllers/MemberController.cs
using CitamChoir.Models;
using CitamChoir.ViewModel;
using Microsoft.AspNet.Identity;
using System;
using System.Linq;
using System.Web.Mvc;

namespace CitamChoir.Controllers
{
    public class MemberController : Controller
    {

        //Get a list of generes from db

        private readonly ApplicationDbContext _context;

        public MemberController()
        {
            _context = new ApplicationDbContext();
        }
        // GET: Member
        public ActionResult Create()
        {
         
            var viewModel = new MembersFormViewModel {
                Occupations = _context.Occupations.ToList(),
                Voices = _context.Voices.ToList(),
                Leaders = _context.Leaders.ToList()

            };

            return View(viewModel);
        }
        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(MembersFormViewModel viewModel)
        {

            if (!ModelState.IsValid)
            {
                viewModel.Occupations = _context.Occupations.ToList();
                viewModel.Voices = _context.Voices.ToList();
                viewModel.Leaders = _context.Leaders.ToList();
                return View("Create",viewModel);
            }

            var member = new Member
            {
                VoiceLeaderId = User.Identity.GetUserId(),
                FirstName = viewModel.FirstName,
                OtherNames = viewModel.OtherNames,
                Gender = viewModel.FialGender,
                OccupationId = viewModel.Occupation,
                Email = viewModel.Email,
                Phone = viewModel.Phone,
                InductionDate = viewModel.GetDateTime(),
                BGV = viewModel.BGV,
                WorshipLeader = viewModel.WorshipLeader,
                LeaderId = viewModel.Leader,
                VoiceId= viewModel.Voice

            };
            try
            {
                _context.Members.Add(member);
                _context.SaveChanges();
            }
            catch (Exception ex)
            {

                
                    string res = ex.Message;
                
            }
           
           

            return RedirectToAction("Index", "Home");

        }
    }


}

CitamChoir/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Citam Valley Road Choir</title>
    <link href="https://fonts.googleapis.com/css?family=Lato" rel="stylesheet">
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("VRoad Database", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("Add Member", "Create", "Member")</li>
                    <li>@Html.ActionLink("Attendance", "Contact", "Home")</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Citam Valley Road Choir</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>